const topic = (category, type, profile, query, required) => ({
  category,
  type,
  profile,
  query,
  required: required || [query.split(/\s+/)[0]],
});

module.exports = [
  // Mobile, tablet, computer
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 S26 자급제', ['삼성', 'S26']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 S26 플러스 자급제', ['삼성', 'S26', '플러스']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 S26 울트라 자급제', ['삼성', 'S26', '울트라']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 Z 플립8 자급제', ['삼성', '플립8']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 A57 자급제', ['삼성', 'A57']),
  topic('digital-pc', 'tablet', 'samsung', '삼성 갤럭시탭 S11', ['삼성', 'S11']),
  topic('digital-pc', 'tablet', 'samsung', '삼성 갤럭시탭 S11 울트라', ['삼성', 'S11', '울트라']),
  topic('digital-pc', 'tablet', 'samsung', '삼성 갤럭시탭 S10 FE', ['삼성', 'S10', 'FE']),
  topic('digital-pc', 'smartwatch', 'samsung', '삼성 갤럭시 워치8', ['삼성', '워치8']),
  topic('digital-pc', 'smartwatch', 'samsung', '삼성 갤럭시 워치8 클래식', ['삼성', '워치8', '클래식']),
  topic('digital-pc', 'audio', 'samsung', '삼성 갤럭시 버즈4', ['삼성', '버즈4']),
  topic('digital-pc', 'audio', 'samsung', '삼성 갤럭시 버즈3 FE', ['삼성', '버즈3', 'FE']),
  topic('digital-pc', 'smartwatch', 'samsung', '삼성 갤럭시 링', ['삼성', '갤럭시', '링']),
  topic('digital-pc', 'laptop', 'samsung', '삼성 갤럭시북5 프로', ['삼성', '갤럭시북5', '프로']),
  topic('digital-pc', 'laptop', 'samsung', '삼성 갤럭시북5 프로 360', ['삼성', '갤럭시북5', '360']),
  topic('digital-pc', 'smartphone', 'apple', '애플 아이폰 17 자급제', ['Apple', '아이폰 17']),
  topic('digital-pc', 'smartphone', 'apple', '애플 아이폰 17 프로 자급제', ['Apple', '17 Pro']),
  topic('digital-pc', 'smartphone', 'apple', '애플 아이폰 17 프로 맥스 자급제', ['Apple', '17 Pro Max']),
  topic('digital-pc', 'smartphone', 'apple', '애플 아이폰 에어 자급제', ['Apple', 'iPhone Air']),
  topic('digital-pc', 'smartphone', 'apple', '애플 아이폰 16e 자급제', ['Apple', '16e']),
  topic('digital-pc', 'tablet', 'apple', '애플 아이패드 A16', ['Apple', 'iPad', 'A16']),
  topic('digital-pc', 'tablet', 'apple', '애플 아이패드 에어 M3 11', ['Apple', 'iPad Air', 'M3']),
  topic('digital-pc', 'tablet', 'apple', '애플 아이패드 에어 M3 13', ['Apple', 'iPad Air', 'M3', '13']),
  topic('digital-pc', 'tablet', 'apple', '애플 아이패드 프로 M5 11', ['Apple', 'iPad Pro', 'M5']),
  topic('digital-pc', 'tablet', 'apple', '애플 아이패드 프로 M5 13', ['Apple', 'iPad Pro', 'M5', '13']),
  topic('digital-pc', 'laptop', 'apple', '애플 맥북에어 M4 13', ['Apple', 'MacBook Air', 'M4']),
  topic('digital-pc', 'laptop', 'apple', '애플 맥북에어 M4 15', ['Apple', 'MacBook Air', 'M4', '15']),
  topic('digital-pc', 'laptop', 'apple', '애플 맥북프로 M5 14', ['Apple', 'MacBook Pro', 'M5']),
  topic('digital-pc', 'smartwatch', 'apple', '애플워치 시리즈 11', ['Apple', 'Watch Series 11']),
  topic('digital-pc', 'smartwatch', 'apple', '애플워치 울트라 3', ['Apple', 'Watch Ultra 3']),
  topic('digital-pc', 'smartwatch', 'apple', '애플워치 SE 3', ['Apple', 'Watch SE 3']),
  topic('digital-pc', 'audio', 'apple', '애플 에어팟 4 액티브 노이즈 캔슬링', ['Apple', 'AirPods 4']),
  topic('digital-pc', 'tracker', 'apple', '애플 에어태그 2', ['Apple', 'AirTag']),
  topic('digital-pc', 'laptop', 'lg', 'LG 그램 2026 노트북', ['LG', '그램']),
  topic('digital-pc', 'laptop', 'lg', 'LG 그램 프로 16 2026', ['LG', '그램 프로', '16']),
  topic('digital-pc', 'display', 'lg', 'LG 울트라기어 OLED 32GS95UE', ['LG', '32GS95UE']),
  topic('digital-pc', 'display', 'lg', 'LG 울트라기어 OLED 45GX950A', ['LG', '45GX950A']),
  topic('digital-pc', 'display', 'lg', 'LG 스마트모니터 MyView', ['LG', 'MyView']),
  topic('digital-pc', 'projector', 'lg', 'LG 시네빔 큐브', ['LG', '시네빔']),

  // Displays, storage, peripherals, charging and gaming
  topic('digital-pc', 'display', 'samsung', '삼성 스마트 모니터 M9', ['삼성', 'M9']),
  topic('digital-pc', 'display', 'samsung', '삼성 오디세이 OLED G8', ['삼성', '오디세이', 'G8']),
  topic('digital-pc', 'display', 'samsung', '삼성 오디세이 G7', ['삼성', '오디세이', 'G7']),
  topic('digital-pc', 'display', 'samsung', '삼성 뷰피니티 S9', ['삼성', 'S9']),
  topic('digital-pc', 'storage', 'samsung', '삼성 포터블 SSD T9', ['삼성', 'T9']),
  topic('digital-pc', 'storage', 'samsung', '삼성 SSD 990 PRO', ['삼성', '990 PRO']),
  topic('digital-pc', 'storage', 'samsung', '삼성 SSD 9100 PRO', ['삼성', '9100 PRO']),
  topic('digital-pc', 'storage', 'sandisk', '샌디스크 익스트림 프로 포터블 SSD', ['샌디스크', '익스트림 프로']),
  topic('digital-pc', 'storage', 'sandisk', '샌디스크 크리에이터 폰 SSD', ['샌디스크', '크리에이터']),
  topic('digital-pc', 'storage', 'western-digital', 'WD 마이 패스포트 외장하드 5TB', ['WD', 'My Passport']),
  topic('digital-pc', 'storage', 'western-digital', 'WD BLACK SN850X SSD', ['WD', 'SN850X']),
  topic('digital-pc', 'input', 'logitech', '로지텍 MX Master 4', ['로지텍', 'MX Master 4']),
  topic('digital-pc', 'input', 'logitech', '로지텍 Lift 버티컬 마우스', ['로지텍', 'Lift']),
  topic('digital-pc', 'input', 'logitech', '로지텍 G PRO X2 SUPERSTRIKE', ['로지텍', 'PRO X2']),
  topic('digital-pc', 'input', 'logitech', '로지텍 G502 X PLUS', ['로지텍', 'G502 X']),
  topic('digital-pc', 'input', 'logitech', '로지텍 G515 TKL', ['로지텍', 'G515']),
  topic('digital-pc', 'input', 'logitech', '로지텍 G915 X LIGHTSPEED', ['로지텍', 'G915 X']),
  topic('digital-pc', 'input', 'logitech', '로지텍 MX Mechanical Mini', ['로지텍', 'MX Mechanical']),
  topic('digital-pc', 'webcam', 'logitech', '로지텍 MX Brio 4K 웹캠', ['로지텍', 'Brio']),
  topic('digital-pc', 'audio', 'logitech', '로지텍 Zone Wireless 2', ['로지텍', 'Zone Wireless 2']),
  topic('digital-pc', 'input', 'logitech', '로지텍 Pebble 2 Combo', ['로지텍', 'Pebble 2']),
  topic('digital-pc', 'charger', 'anker', '앤커 프라임 250W 충전기', ['Anker', 'Prime', '250W']),
  topic('digital-pc', 'charger', 'anker', '앤커 프라임 27650mAh 보조배터리', ['Anker', 'Prime', '27650']),
  topic('digital-pc', 'charger', 'anker', '앤커 나노 100W 충전기', ['Anker', 'Nano', '100W']),
  topic('digital-pc', 'charger', 'anker', '앤커 맥고 Qi2 보조배터리', ['Anker', 'MagGo']),
  topic('digital-pc', 'audio', 'anker', '앤커 사운드코어 리버티 5', ['soundcore', 'Liberty 5']),
  topic('digital-pc', 'console', 'sony', '소니 플레이스테이션5 슬림 디스크', ['플레이스테이션5', '슬림']),
  topic('digital-pc', 'console', 'sony', '소니 플레이스테이션 포털 리모트 플레이어', ['플레이스테이션', '포털']),
  topic('digital-pc', 'console', 'sony', '소니 듀얼센스 엣지', ['듀얼센스', '엣지']),
  topic('digital-pc', 'console', 'nintendo', '닌텐도 스위치2', ['닌텐도', '스위치2']),
  topic('digital-pc', 'console', 'nintendo', '닌텐도 스위치 OLED', ['닌텐도', 'OLED']),
  topic('digital-pc', 'console', 'microsoft', '엑스박스 시리즈 X', ['Xbox', 'Series X']),

  // Audio, TV and camera
  topic('digital-pc', 'audio', 'sony', '소니 WH-1000XM6', ['소니', 'WH-1000XM6']),
  topic('digital-pc', 'audio', 'sony', '소니 WF-1000XM5', ['소니', 'WF-1000XM5']),
  topic('digital-pc', 'audio', 'sony', '소니 ULT WEAR', ['소니', 'ULT WEAR']),
  topic('digital-pc', 'audio', 'sony', '소니 LinkBuds Fit', ['소니', 'LinkBuds Fit']),
  topic('digital-pc', 'audio', 'bose', '보스 QC 울트라 헤드폰 2세대', ['BOSE', 'QC 울트라']),
  topic('digital-pc', 'audio', 'bose', '보스 QC 울트라 이어버드 2세대', ['BOSE', 'QC 울트라', '이어버드']),
  topic('digital-pc', 'audio', 'bose', '보스 사운드링크 맥스', ['BOSE', 'SoundLink Max']),
  topic('digital-pc', 'audio', 'bose', '보스 사운드링크 플렉스 2세대', ['BOSE', 'SoundLink Flex']),
  topic('digital-pc', 'audio', 'jbl', 'JBL 투어 프로 3', ['JBL', 'TOUR PRO 3']),
  topic('digital-pc', 'audio', 'jbl', 'JBL 차지 6', ['JBL', 'CHARGE 6']),
  topic('digital-pc', 'audio', 'jbl', 'JBL 플립 7', ['JBL', 'FLIP 7']),
  topic('digital-pc', 'audio', 'marshall', '마샬 액톤3 블루투스 스피커', ['마샬', '액톤3']),
  topic('digital-pc', 'audio', 'marshall', '마샬 엠버튼3 블루투스 스피커', ['마샬', '엠버튼3']),
  topic('digital-pc', 'tv', 'samsung', '삼성 OLED TV S95F', ['삼성', 'S95F']),
  topic('digital-pc', 'tv', 'samsung', '삼성 Neo QLED 8K QN900F', ['삼성', 'QN900F']),
  topic('digital-pc', 'tv', 'samsung', '삼성 더 프레임 프로 TV', ['삼성', '더 프레임']),
  topic('digital-pc', 'projector', 'samsung', '삼성 더 프리스타일 2세대', ['삼성', '프리스타일']),
  topic('digital-pc', 'tv', 'lg', 'LG OLED evo G5 TV', ['LG', 'OLED', 'G5']),
  topic('digital-pc', 'tv', 'lg', 'LG OLED evo C5 TV', ['LG', 'OLED', 'C5']),
  topic('digital-pc', 'tv', 'sony', '소니 브라비아 8 II OLED TV', ['소니', 'BRAVIA 8']),
  topic('digital-pc', 'camera', 'sony', '소니 알파 A7C II', ['소니', 'A7C II']),
  topic('digital-pc', 'camera', 'sony', '소니 ZV-E10 II', ['소니', 'ZV-E10 II']),
  topic('digital-pc', 'camera', 'sony', '소니 FE 24-70mm F2.8 GM II', ['소니', '24-70', 'GM II']),
  topic('digital-pc', 'camera', 'dji', 'DJI Osmo 360', ['DJI', 'Osmo 360']),
  topic('digital-pc', 'camera', 'dji', 'DJI Mic Mini', ['DJI', 'Mic Mini']),
  topic('digital-pc', 'camera', 'dji', 'DJI Mic 2', ['DJI', 'Mic 2']),
  topic('digital-pc', 'drone', 'dji', 'DJI Mini 4 Pro', ['DJI', 'Mini 4 Pro']),
  topic('digital-pc', 'drone', 'dji', 'DJI Flip 드론', ['DJI', 'Flip']),
  topic('digital-pc', 'drone', 'dji', 'DJI Neo 드론', ['DJI', 'Neo']),
  topic('digital-pc', 'camera', 'insta360', '인스타360 Ace Pro 2', ['인스타360', 'Ace Pro 2']),
  topic('digital-pc', 'camera', 'insta360', '인스타360 GO 3S', ['인스타360', 'GO 3S']),
  topic('digital-pc', 'gimbal', 'insta360', '인스타360 Flow 2 Pro', ['인스타360', 'Flow 2 Pro']),
  topic('digital-pc', 'webcam', 'insta360', '인스타360 Link 2 웹캠', ['인스타360', 'Link 2']),
  topic('digital-pc', 'camera', 'gopro', '고프로 HERO13 Black', ['GoPro', 'HERO13']),
  topic('digital-pc', 'camera', 'gopro', '고프로 MAX 2', ['GoPro', 'MAX 2']),

  // Cleaning, air, laundry and large appliances
  topic('home-appliances', 'vacuum', 'dyson', '다이슨 V16 Piston Animal', ['다이슨', 'V16']),
  topic('home-appliances', 'vacuum', 'dyson', '다이슨 Gen5 Detect', ['다이슨', 'Gen5']),
  topic('home-appliances', 'vacuum', 'dyson', '다이슨 V12 Detect Slim', ['다이슨', 'V12']),
  topic('home-appliances', 'wetCleaner', 'dyson', '다이슨 WashG1', ['다이슨', 'WashG1']),
  topic('home-appliances', 'robotVacuum', 'lg', 'LG 로보킹 AI 올인원', ['LG', '로보킹']),
  topic('home-appliances', 'vacuum', 'lg', 'LG 코드제로 A9 AI', ['LG', '코드제로', 'A9']),
  topic('home-appliances', 'robotVacuum', 'samsung', '삼성 비스포크 AI 스팀 로봇청소기', ['삼성', 'AI 스팀']),
  topic('home-appliances', 'vacuum', 'samsung', '삼성 비스포크 AI 제트 울트라', ['삼성', 'AI 제트']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 Saros 10', ['로보락', 'Saros 10']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 Saros 10R', ['로보락', 'Saros 10R']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 S9 MaxV Ultra', ['로보락', 'S9 MaxV']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 Qrevo Curv', ['로보락', 'Qrevo Curv']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 Qrevo Edge', ['로보락', 'Qrevo Edge']),
  topic('home-appliances', 'wetCleaner', 'roborock', '로보락 Flexi Pro', ['로보락', 'Flexi Pro']),
  topic('home-appliances', 'vacuum', 'roborock', '로보락 H60 Ultra', ['로보락', 'H60']),
  topic('home-appliances', 'robotVacuum', 'dreame', '드리미 X50 Ultra', ['드리미', 'X50']),
  topic('home-appliances', 'robotVacuum', 'dreame', '드리미 L50 Pro Ultra', ['드리미', 'L50']),
  topic('home-appliances', 'wetCleaner', 'dreame', '드리미 H15 Pro Heat', ['드리미', 'H15']),
  topic('home-appliances', 'vacuum', 'dreame', '드리미 Z30', ['드리미', 'Z30']),
  topic('home-appliances', 'robotVacuum', 'xiaomi', '샤오미 로봇청소기 X20 Max', ['샤오미', 'X20 Max']),
  topic('home-appliances', 'airCare', 'lg', 'LG 퓨리케어 360 공기청정기', ['LG', '퓨리케어', '360']),
  topic('home-appliances', 'airCare', 'lg', 'LG 퓨리케어 에어로퍼니처', ['LG', '에어로퍼니처']),
  topic('home-appliances', 'dehumidifier', 'lg', 'LG 휘센 듀얼 인버터 제습기', ['LG', '휘센', '제습기']),
  topic('home-appliances', 'airCare', 'samsung', '삼성 블루스카이 공기청정기', ['삼성', '블루스카이']),
  topic('home-appliances', 'dehumidifier', 'samsung', '삼성 인버터 제습기', ['삼성', '제습기']),
  topic('home-appliances', 'airCare', 'winix', '위닉스 타워 프라임 공기청정기', ['위닉스', '타워 프라임']),
  topic('home-appliances', 'dehumidifier', 'winix', '위닉스 뽀송 인버터 제습기', ['위닉스', '뽀송']),
  topic('home-appliances', 'airCare', 'coway', '코웨이 노블 공기청정기2', ['코웨이', '노블']),
  topic('home-appliances', 'airCare', 'blueair', '블루에어 헬스프로텍트 공기청정기', ['블루에어', '헬스프로텍트']),
  topic('home-appliances', 'airCare', 'dyson', '다이슨 빅앤콰이엇 공기청정기', ['다이슨', '빅앤콰이엇']),
  topic('home-appliances', 'airCare', 'dyson', '다이슨 핫앤쿨 HP2', ['다이슨', 'HP2']),
  topic('home-appliances', 'laundry', 'lg', 'LG 워시타워 AI', ['LG', '워시타워']),
  topic('home-appliances', 'laundry', 'lg', 'LG 워시콤보 오브제컬렉션', ['LG', '워시콤보']),
  topic('home-appliances', 'laundry', 'lg', 'LG 스타일러 5벌', ['LG', '스타일러']),
  topic('home-appliances', 'laundry', 'samsung', '삼성 비스포크 AI 콤보', ['삼성', 'AI 콤보']),
  topic('home-appliances', 'laundry', 'samsung', '삼성 비스포크 AI 원바디', ['삼성', 'AI 원바디']),
  topic('home-appliances', 'dishwasher', 'lg', 'LG 디오스 오브제컬렉션 식기세척기 14인용', ['LG', '식기세척기', '14']),
  topic('home-appliances', 'dishwasher', 'samsung', '삼성 비스포크 AI 식기세척기 14인용', ['삼성', '식기세척기', '14']),
  topic('home-appliances', 'refrigerator', 'lg', 'LG 디오스 오브제컬렉션 냉장고', ['LG', '디오스', '냉장고']),
  topic('home-appliances', 'refrigerator', 'samsung', '삼성 비스포크 AI 하이브리드 냉장고', ['삼성', '하이브리드', '냉장고']),

  // Kitchen and coffee
  topic('living-kitchen', 'cooking', 'ninja', '닌자 푸디 듀얼존 에어프라이어', ['닌자', '듀얼존']),
  topic('living-kitchen', 'blender', 'ninja', '닌자 디텍트 파워 블렌더 프로', ['닌자', '디텍트']),
  topic('living-kitchen', 'beverage', 'ninja', '닌자 슬러시 프로즌 드링크 메이커', ['닌자', '슬러시']),
  topic('living-kitchen', 'blender', 'ninja', '닌자 블라스트 휴대용 블렌더', ['닌자', '블라스트']),
  topic('living-kitchen', 'cooking', 'ninja', '닌자 크리스피 에어프라이어', ['닌자', '크리스피']),
  topic('living-kitchen', 'cooking', 'ninja', '닌자 콤비 멀티쿠커', ['닌자', '콤비']),
  topic('living-kitchen', 'cooking', 'philips', '필립스 에어프라이어 5000 시리즈', ['필립스', '5000']),
  topic('living-kitchen', 'cooking', 'philips', '필립스 에어프라이어 7000 시리즈', ['필립스', '7000']),
  topic('living-kitchen', 'coffee', 'philips', '필립스 라떼고 5500', ['필립스', '라떼고', '5500']),
  topic('living-kitchen', 'coffee', 'philips', '필립스 바리스티나 에스프레소 머신', ['필립스', '바리스티나']),
  topic('living-kitchen', 'cooking', 'philips', '필립스 올인원 쿠커', ['필립스', '올인원']),
  topic('living-kitchen', 'kettle', 'philips', '필립스 무선 전기주전자', ['필립스', '전기주전자']),
  topic('living-kitchen', 'coffee', 'nespresso', '네스프레소 버츄오 팝', ['네스프레소', '버츄오 팝']),
  topic('living-kitchen', 'coffee', 'nespresso', '네스프레소 버츄오 플러스', ['네스프레소', '버츄오 플러스']),
  topic('living-kitchen', 'coffee', 'nespresso', '네스프레소 버츄오 크리아티스타', ['네스프레소', '크리아티스타']),
  topic('living-kitchen', 'coffee', 'nespresso', '네스프레소 에센자 미니', ['네스프레소', '에센자 미니']),
  topic('living-kitchen', 'coffee', 'nespresso', '네스프레소 시티즈 플래티넘', ['네스프레소', '시티즈']),
  topic('living-kitchen', 'coffee', 'delonghi', '드롱기 리벨리아 전자동 커피머신', ['드롱기', '리벨리아']),
  topic('living-kitchen', 'coffee', 'delonghi', '드롱기 마그니피카 에보', ['드롱기', '마그니피카 에보']),
  topic('living-kitchen', 'coffee', 'delonghi', '드롱기 디나미카 플러스', ['드롱기', '디나미카']),
  topic('living-kitchen', 'coffee', 'delonghi', '드롱기 라스페셜리스타 아르떼', ['드롱기', '라스페셜리스타']),
  topic('living-kitchen', 'coffee', 'delonghi', '드롱기 데디카 커피머신', ['드롱기', '데디카']),
  topic('living-kitchen', 'riceCooker', 'cuckoo', '쿠쿠 마스터셰프 사일런스 밥솥', ['쿠쿠', '마스터셰프']),
  topic('living-kitchen', 'riceCooker', 'cuckoo', '쿠쿠 트윈프레셔 밥솥', ['쿠쿠', '트윈프레셔']),
  topic('living-kitchen', 'riceCooker', 'cuchen', '쿠첸 브레인 밥솥', ['쿠첸', '브레인']),
  topic('living-kitchen', 'riceCooker', 'cuchen', '쿠첸 121 플러스 밥솥', ['쿠첸', '121']),
  topic('living-kitchen', 'cooking', 'tefal', '테팔 원픽냄비팬', ['테팔', '원픽']),
  topic('living-kitchen', 'cooking', 'tefal', '테팔 매직핸즈 인덕션', ['테팔', '매직핸즈']),
  topic('living-kitchen', 'storageKitchen', 'locknlock', '락앤락 메트로 킹 텀블러', ['락앤락', '메트로 킹']),
  topic('living-kitchen', 'storageKitchen', 'locknlock', '락앤락 바로한끼 도자기 밥용기', ['락앤락', '바로한끼']),

  // Grooming and beauty devices
  topic('fashion-beauty', 'hairCare', 'dyson', '다이슨 에어랩 i.d.', ['다이슨', '에어랩']),
  topic('fashion-beauty', 'hairCare', 'dyson', '다이슨 슈퍼소닉 뉴럴', ['다이슨', '뉴럴']),
  topic('fashion-beauty', 'hairCare', 'dyson', '다이슨 에어스트레이트', ['다이슨', '에어스트레이트']),
  topic('fashion-beauty', 'shaver', 'braun', '브라운 시리즈9 PRO 플러스', ['브라운', '시리즈9']),
  topic('fashion-beauty', 'shaver', 'braun', '브라운 시리즈8 전기면도기', ['브라운', '시리즈8']),
  topic('fashion-beauty', 'shaver', 'braun', '브라운 시리즈7 전기면도기', ['브라운', '시리즈7']),
  topic('fashion-beauty', 'beautyDevice', 'braun', '브라운 스킨아이엑스퍼트 IPL', ['브라운', '스킨아이엑스퍼트']),
  topic('fashion-beauty', 'shaver', 'philips', '필립스 i9000 프레스티지 면도기', ['필립스', 'i9000']),
  topic('fashion-beauty', 'shaver', 'philips', '필립스 S9000 프레스티지 면도기', ['필립스', 'S9000']),
  topic('fashion-beauty', 'shaver', 'philips', '필립스 원블레이드 프로 360', ['필립스', '원블레이드']),
  topic('fashion-beauty', 'beautyDevice', 'philips', '필립스 루메아 IPL', ['필립스', '루메아']),
  topic('fashion-beauty', 'hairCare', 'panasonic', '파나소닉 나노케어 드라이어', ['파나소닉', '나노케어']),
  topic('fashion-beauty', 'shaver', 'panasonic', '파나소닉 람대쉬 프로 전기면도기', ['파나소닉', '람대쉬']),
  topic('fashion-beauty', 'oralCare', 'panasonic', '파나소닉 제트워셔 구강세정기', ['파나소닉', '제트워셔']),
  topic('fashion-beauty', 'hairCare', 'jmw', 'JMW 에어스톰 드라이기', ['JMW', '에어스톰']),
  topic('fashion-beauty', 'oralCare', 'philips', '필립스 소닉케어 9900 프레스티지', ['필립스', '9900']),

  // Wearables, outdoor power and family/pet
  topic('outdoor-auto', 'smartwatch', 'garmin', '가민 포러너 970', ['가민', '포러너 970']),
  topic('outdoor-auto', 'smartwatch', 'garmin', '가민 포러너 570', ['가민', '포러너 570']),
  topic('outdoor-auto', 'smartwatch', 'garmin', '가민 피닉스 8', ['가민', '피닉스 8']),
  topic('outdoor-auto', 'bikeComputer', 'garmin', '가민 엣지 1050', ['가민', '엣지 1050']),
  topic('outdoor-auto', 'outdoorPower', 'ecoflow', '에코플로우 델타3 플러스', ['에코플로우', '델타3']),
  topic('outdoor-auto', 'outdoorPower', 'ecoflow', '에코플로우 리버3 플러스', ['에코플로우', '리버3']),
  topic('outdoor-auto', 'outdoorPower', 'jackery', '재키리 익스플로러 1000 뉴', ['Jackery', '1000']),
  topic('outdoor-auto', 'outdoorPower', 'bluetti', '블루에티 AC180 파워뱅크', ['BLUETTI', 'AC180']),
  topic('outdoor-auto', 'dashcam', 'blackvue', '블랙뷰 DR970X 블랙박스', ['블랙뷰', 'DR970X']),
  topic('outdoor-auto', 'carAccessory', 'xiaomi', '샤오미 휴대용 에어펌프 2 프로', ['샤오미', '에어펌프']),
  topic('pet-family', 'petFeeder', 'petlibro', '펫리브로 그라나리 자동급식기', ['PETLIBRO', 'Granary']),
  topic('pet-family', 'petFountain', 'petlibro', '펫리브로 도크스트림 고양이 정수기', ['PETLIBRO', 'Dockstream']),
  topic('pet-family', 'petFountain', 'xiaomi', '샤오미 스마트 펫 정수기 2', ['샤오미', '펫 정수기']),
  topic('pet-family', 'petCare', 'dyson', '다이슨 펫 그루밍 툴', ['다이슨', '그루밍']),
  topic('pet-family', 'babyMonitor', 'philips', '필립스 아벤트 비디오 베이비 모니터', ['필립스', '아벤트']),
  topic('pet-family', 'sterilizer', 'babybrezza', '베이비브레짜 젖병 세척기', ['베이비브레짜', '세척기']),
];
