const topic = (category, type, profile, query, required, forbidden = []) => ({ category, type, profile, query, required, forbidden });

module.exports = [
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 S25 자급제', ['삼성', 'S25'], ['플러스', '울트라', 'FE']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 S25 플러스 자급제', ['삼성', 'S25', '플러스']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 S25 울트라 자급제', ['삼성', 'S25', '울트라']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 Z 폴드7 자급제', ['삼성', '폴드7']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 Z 플립7 자급제', ['삼성', '플립7']),
  topic('digital-pc', 'smartphone', 'samsung', '삼성 갤럭시 A56 자급제', ['삼성', 'A56']),
  topic('digital-pc', 'tablet', 'samsung', '삼성 갤럭시탭 S10 울트라', ['삼성', 'S10', '울트라']),
  topic('digital-pc', 'tablet', 'samsung', '삼성 갤럭시탭 S10 플러스', ['삼성', 'S10', '플러스']),
  topic('digital-pc', 'tablet', 'samsung', '삼성 갤럭시탭 A9 플러스', ['삼성', 'A9']),
  topic('digital-pc', 'laptop', 'samsung', '삼성 갤럭시북4 프로', ['삼성', '갤럭시북4', '프로']),
  topic('digital-pc', 'laptop', 'samsung', '삼성 갤럭시북4 엣지', ['삼성', '갤럭시북4', '엣지']),
  topic('digital-pc', 'smartphone', 'apple', 'Apple 아이폰 16 자급제', ['Apple', '아이폰 16'], ['Pro', 'Plus', '프로', '플러스']),
  topic('digital-pc', 'smartphone', 'apple', 'Apple 아이폰 16 Pro 자급제', ['Apple', '16 Pro']),
  topic('digital-pc', 'smartphone', 'apple', 'Apple 아이폰 15 자급제', ['Apple', '아이폰 15'], ['Pro', 'Plus', '프로', '플러스']),
  topic('digital-pc', 'tablet', 'apple', 'Apple 아이패드 10세대', ['Apple', 'iPad', '10']),
  topic('digital-pc', 'tablet', 'apple', 'Apple 아이패드 에어 M2 11', ['Apple', 'iPad Air', 'M2']),
  topic('digital-pc', 'tablet', 'apple', 'Apple 아이패드 프로 M4 11', ['Apple', 'iPad Pro', 'M4']),
  topic('digital-pc', 'laptop', 'apple', 'Apple 맥북에어 M3 13', ['Apple', 'MacBook Air', 'M3']),
  topic('digital-pc', 'smartwatch', 'apple', 'Apple 애플워치 시리즈 10', ['Apple', 'Watch Series 10']),
  topic('digital-pc', 'smartwatch', 'apple', 'Apple 애플워치 울트라 2', ['Apple', 'Watch Ultra 2']),
  topic('digital-pc', 'audio', 'apple', 'Apple 에어팟 4', ['Apple', 'AirPods 4']),
  topic('digital-pc', 'audio', 'apple', 'Apple 에어팟 맥스 USB C', ['Apple', 'AirPods Max']),
  topic('digital-pc', 'laptop', 'lg', 'LG 그램 프로 16 2025', ['LG', '그램 프로', '16', '2025']),
  topic('digital-pc', 'laptop', 'lg', 'LG 울트라PC 노트북', ['LG', '울트라PC']),
  topic('digital-pc', 'display', 'lg', 'LG 27UP850 4K 모니터', ['LG', '27UP850']),
  topic('digital-pc', 'audio', 'sony', '소니 WH-1000XM5', ['소니', 'WH-1000XM5']),
  topic('digital-pc', 'audio', 'sony', '소니 SRS-XB100', ['소니', 'XB100']),
  topic('digital-pc', 'camera', 'sony', '소니 ZV-1 II', ['소니', 'ZV-1']),
  topic('digital-pc', 'camera', 'canon', '캐논 EOS R50', ['캐논', 'EOS R50']),
  topic('digital-pc', 'camera', 'canon', '캐논 EOS R8', ['캐논', 'EOS R8']),
  topic('digital-pc', 'camera', 'canon', '캐논 파워샷 V1', ['캐논', 'PowerShot V1']),
  topic('digital-pc', 'input', 'razer', '레이저 데스에더 V3 프로', ['레이저', '데스에더 V3']),
  topic('digital-pc', 'input', 'razer', '레이저 바이퍼 V3 프로', ['레이저', '바이퍼 V3']),
  topic('digital-pc', 'input', 'razer', '레이저 블랙위도우 V4', ['레이저', '블랙위도우 V4']),
  topic('digital-pc', 'input', 'corsair', '커세어 K70 MAX 키보드', ['커세어', 'K70 MAX']),
  topic('digital-pc', 'audio', 'corsair', '커세어 VOID v2 헤드셋', ['커세어', 'VOID']),
  topic('digital-pc', 'laptop', 'asus', '에이수스 ROG 제피러스 G14', ['에이수스', '제피러스', 'G14']),
  topic('digital-pc', 'laptop', 'asus', '에이수스 젠북 S 14', ['에이수스', '젠북', '14']),
  topic('digital-pc', 'laptop', 'lenovo', '레노버 리전 5 프로', ['레노버', '리전', '5']),
  topic('digital-pc', 'laptop', 'lenovo', '레노버 요가 슬림 7i', ['레노버', '요가', '7']),
  topic('digital-pc', 'laptop', 'hp', 'HP 오멘 16 노트북', ['HP', '오멘', '16']),
  topic('digital-pc', 'display', 'dell', '델 울트라샤프 U2725QE', ['Dell', 'U2725QE']),

  topic('home-appliances', 'vacuum', 'dyson', '다이슨 V15 Detect', ['다이슨', 'V15']),
  topic('home-appliances', 'vacuum', 'dyson', '다이슨 V12 Detect Slim', ['다이슨', 'V12']),
  topic('home-appliances', 'wetCleaner', 'dyson', '다이슨 WashG1 물청소기', ['다이슨', 'WashG1']),
  topic('home-appliances', 'vacuum', 'dyson', '다이슨 옴니글라이드', ['다이슨', '옴니글라이드']),
  topic('home-appliances', 'vacuum', 'lg', 'LG 코드제로 A9S', ['LG', '코드제로', 'A9S']),
  topic('home-appliances', 'robotVacuum', 'lg', 'LG 로보킹 AI 본체', ['LG', '로보킹', 'AI']),
  topic('home-appliances', 'vacuum', 'samsung', '삼성 비스포크 제트 AI', ['삼성', '비스포크', '제트']),
  topic('home-appliances', 'robotVacuum', 'samsung', '삼성 비스포크 제트 봇 AI', ['삼성', '제트 봇']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 S8 MaxV Ultra', ['로보락', 'S8 MaxV']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 Qrevo Master', ['로보락', 'Qrevo Master']),
  topic('home-appliances', 'robotVacuum', 'roborock', '로보락 Q8 Max Plus', ['로보락', 'Q8 Max']),
  topic('home-appliances', 'robotVacuum', 'dreame', '드리미 L40 Ultra', ['드리미', 'L40']),
  topic('home-appliances', 'robotVacuum', 'dreame', '드리미 X40 Ultra', ['드리미', 'X40']),
  topic('home-appliances', 'robotVacuum', 'ecovacs', '에코백스 디봇 X8 프로 옴니', ['에코백스', 'X8']),
  topic('home-appliances', 'robotVacuum', 'ecovacs', '에코백스 디봇 T50 프로 옴니', ['에코백스', 'T50']),
  topic('home-appliances', 'airCare', 'winix', '위닉스 타워엣지 공기청정기', ['위닉스', '타워엣지']),
  topic('home-appliances', 'dehumidifier', 'winix', '위닉스 뽀송 제습기 21L', ['위닉스', '뽀송', '21L']),
  topic('home-appliances', 'airCare', 'coway', '코웨이 에어 카트리지 공기청정기', ['코웨이', '에어 카트리지']),
  topic('home-appliances', 'airCare', 'electrolux', '일렉트로룩스 퓨어 A9 공기청정기', ['일렉트로룩스', '퓨어 A9']),
  topic('home-appliances', 'dehumidifier', 'carrier', '캐리어 클라윈드 제습기 20L', ['캐리어', '제습기', '20L']),
  topic('home-appliances', 'laundry', 'lg', 'LG 트롬 세탁기 25kg', ['LG', '트롬', '25kg']),
  topic('home-appliances', 'laundry', 'lg', 'LG 트롬 건조기 21kg', ['LG', '트롬', '건조기']),
  topic('home-appliances', 'laundry', 'samsung', '삼성 비스포크 그랑데 세탁기 25kg', ['삼성', '그랑데', '세탁기']),
  topic('home-appliances', 'laundry', 'samsung', '삼성 비스포크 그랑데 건조기 21kg', ['삼성', '그랑데', '건조기']),
  topic('home-appliances', 'dishwasher', 'skmagic', 'SK매직 트리플케어 식기세척기', ['SK매직', '트리플케어']),
  topic('home-appliances', 'refrigerator', 'lg', 'LG 디오스 김치톡톡 김치냉장고', ['LG', '김치톡톡']),
  topic('home-appliances', 'refrigerator', 'samsung', '삼성 비스포크 김치플러스 김치냉장고', ['삼성', '김치플러스']),

  topic('living-kitchen', 'cooking', 'cuckoo', '쿠쿠 에어프라이어 5.5L', ['쿠쿠', '에어프라이어']),
  topic('living-kitchen', 'riceCooker', 'cuckoo', '쿠쿠 트윈프레셔 6인용 밥솥', ['쿠쿠', '트윈프레셔', '6인용']),
  topic('living-kitchen', 'riceCooker', 'cuckoo', '쿠쿠 트윈프레셔 10인용 밥솥', ['쿠쿠', '트윈프레셔', '10인용']),
  topic('living-kitchen', 'riceCooker', 'cuchen', '쿠첸 브레인 6인용 밥솥', ['쿠첸', '브레인', '6인용']),
  topic('living-kitchen', 'riceCooker', 'cuchen', '쿠첸 121 플러스 6인용', ['쿠첸', '121', '6인용']),
  topic('living-kitchen', 'cooking', 'tefal', '테팔 이지프라이 그릴 앤 스팀', ['테팔', '이지프라이']),
  topic('living-kitchen', 'blender', 'vitamix', '바이타믹스 A3500i 블렌더', ['바이타믹스', 'A3500']),
  topic('living-kitchen', 'blender', 'blendtec', '블렌텍 디자이너 625 블렌더', ['블렌텍', '625']),
  topic('living-kitchen', 'cooking', 'balmuda', '발뮤다 더 토스터', ['발뮤다', '토스터']),
  topic('living-kitchen', 'kettle', 'balmuda', '발뮤다 더 팟 전기주전자', ['발뮤다', '더 팟']),
  topic('living-kitchen', 'cooking', 'panasonic', '파나소닉 스팀오븐 NU-SC300B', ['파나소닉', 'NU-SC300B']),
  topic('living-kitchen', 'coffee', 'jura', '유라 E8 전자동 커피머신', ['유라', 'E8']),
  topic('living-kitchen', 'coffee', 'breville', '브레빌 바리스타 익스프레스', ['브레빌', '바리스타 익스프레스']),
  topic('living-kitchen', 'coffee', 'breville', '브레빌 밤비노 플러스', ['브레빌', '밤비노']),
  topic('living-kitchen', 'coffee', 'illy', '일리 Y3.3 캡슐 커피머신', ['일리', 'Y3.3']),
  topic('living-kitchen', 'storageKitchen', 'stanley', '스탠리 퀜처 H2.0 텀블러', ['스탠리', '퀜처']),
  topic('living-kitchen', 'storageKitchen', 'thermos', '써모스 데일리 원터치 텀블러', ['써모스', '원터치']),

  topic('fashion-beauty', 'hairCare', 'dyson', '다이슨 에어랩 오리진', ['다이슨', '에어랩', '오리진']),
  topic('fashion-beauty', 'shaver', 'braun', '브라운 시리즈9 프로 플러스 본품', ['브라운', '시리즈9', '면도기']),
  topic('fashion-beauty', 'shaver', 'braun', '브라운 시리즈8 면도기 본체', ['브라운', '시리즈8', '면도기']),
  topic('fashion-beauty', 'shaver', 'philips', '필립스 S9000 전기면도기', ['필립스', 'S9000', '면도기']),
  topic('fashion-beauty', 'shaver', 'philips', '필립스 i9000 전기면도기', ['필립스', 'i9000', '면도기']),
  topic('fashion-beauty', 'beautyDevice', 'panasonic', '파나소닉 바이탈리프트 RF', ['파나소닉', '바이탈리프트']),
  topic('fashion-beauty', 'beautyDevice', 'lg', 'LG 프라엘 더마쎄라', ['LG', '프라엘', '더마쎄라']),
  topic('fashion-beauty', 'oralCare', 'oralb', '오랄비 iO10 전동칫솔', ['오랄비', 'iO10']),

  topic('outdoor-auto', 'smartwatch', 'garmin', '가민 인스팅트 3', ['가민', '인스팅트 3']),
  topic('outdoor-auto', 'smartwatch', 'garmin', '가민 베뉴 3', ['가민', '베뉴 3']),
  topic('outdoor-auto', 'bikeComputer', 'garmin', '가민 엣지 840', ['가민', '엣지 840']),
  topic('outdoor-auto', 'outdoorPower', 'ecoflow', '에코플로우 델타2 맥스', ['에코플로우', '델타2 맥스']),
  topic('outdoor-auto', 'outdoorPower', 'ecoflow', '에코플로우 리버2 프로', ['에코플로우', '리버2 프로']),
  topic('outdoor-auto', 'outdoorPower', 'jackery', '재키리 익스플로러 1000 플러스', ['Jackery', '1000 Plus']),
  topic('outdoor-auto', 'dashcam', 'blackvue', '블랙뷰 DR970X Plus 2채널', ['블랙뷰', 'DR970X', '2채널']),
  topic('outdoor-auto', 'dashcam', 'thinkware', '아이나비 QXD1 블랙박스', ['아이나비', 'QXD1']),
  topic('outdoor-auto', 'dashcam', 'thinkware', '아이나비 Z9000 블랙박스', ['아이나비', 'Z9000']),
  topic('outdoor-auto', 'dashcam', 'iroad', '아이로드 X30 블랙박스', ['아이로드', 'X30']),

  topic('pet-family', 'petFeeder', 'petkit', '펫킷 프레시 엘리먼트 자동급식기', ['펫킷', '자동급식기']),
  topic('pet-family', 'petFountain', 'petkit', '펫킷 에버스위트 정수기', ['펫킷', '에버스위트']),
  topic('pet-family', 'petFeeder', 'petlibro', 'PETLIBRO 그라나리 자동급식기', ['PETLIBRO', 'Granary']),
  topic('pet-family', 'petFountain', 'petlibro', 'PETLIBRO Dockstream 정수기', ['PETLIBRO', 'Dockstream']),
  topic('pet-family', 'petFeeder', 'petsafe', '펫세이프 스마트 피드 자동급식기', ['PetSafe', 'Smart Feed']),
  topic('pet-family', 'petCare', 'catlink', '캣링크 스쿠퍼 럭셔리 프로 자동화장실', ['캣링크', '스쿠퍼']),
  topic('pet-family', 'babyMonitor', 'philips', '필립스 아벤트 커넥티드 베이비 모니터', ['필립스', '아벤트', '모니터']),
  topic('pet-family', 'sterilizer', 'babybrezza', '베이비브레짜 포뮬러 프로 어드밴스드', ['베이비브레짜', '포뮬러 프로']),
  topic('pet-family', 'babyMonitor', 'motorola', '모토로라 VM855 베이비 모니터', ['모토로라', 'VM855']),
  topic('pet-family', 'stroller', 'nuna', '뉴나 트리브 넥스트 유모차', ['뉴나', '트리브']),
  topic('pet-family', 'carSeat', 'joie', '조이 아이스핀 360 카시트', ['조이', '아이스핀']),
];
